### ISSUE TITLE
Proposition:

### ISSUE THREAD

**Issue by michaelaye** [wtolson/pysis#11]
I propose to change CubeFile to examine the input type, and if it's a string, to automatically open the filestream. This, to avoid the, IMHO, cumbersome CubeFile.open API.
If you agree, I can do a PR?

Edited: i confused my derived class RingCube with your CubeFile class.

**Comment by michaelaye** [comment]
Maybe leave the existing .open for backwards compatibility of course, so that no code changes are required for older code.

**Comment by wtolson** [comment]
Sounds good to me. Looking forward to your PR.
