### ISSUE TITLE
pysis.env.ISIS_PATH and ISIS_ROOT settings not respected

### ISSUE THREAD

**Issue by michaelaye** [wtolson/pysis#19]
I don't know how pysis sets these and when, but when I saw that I can change the values of `pysis.env.ISIS_PATH` and `_ROOT` I was hoping that I can point `pysis` to a parallel ISIS3 install I have where I fixed an ISIS3 bug.
Can you confirm if this should be working or if I misinterpret things and how else I could work with a temporary ISIS3 setup?

**Comment by wtolson** [comment]
The value of `pysis.env.ISIS_PATH` gets set from the environmental variable `ISISROOT` and `pysis.env.ISIS_PATH` gets set to `$ISISPATH/bin`.

You can over ride it with:

```shell
export ISISROOT=/path/to/my/isis
python myscript.py
```

https://github.com/wtolson/pysis/blob/master/pysis/env.py#L19

**Comment by wtolson** [comment]
Going to close this for now. Let me know if you are still running into problems @michaelaye.

**Comment by michaelaye** [comment]
Any clue why it doesn't work with jupyter notebooks though, as described? The notebook was launched in an ENV with the new ISISROOT active?

**Comment by michaelaye** [comment]
Ah, sorry, must have been dreaming that I described this. ;)

**Comment by wtolson** [comment]
Interesting, jupyter is probably reseting the env variables for the notebooks, try setting `ISISROOT` at the top of your notebook:

```python
import os
os.environ['ISISROOT'] = '/path/to/isis/'

import isis
...
```

**Comment by wtolson** [comment]
Alternatively you could create your own isis instance:

```pythonn
from pyisis import Isis

isis = Isis(path='/my/custom/isis/path')
isis.mdis2isis(from_=img_name, to=cub_name)
```

**Comment by michaelaye** [comment]
Both methods were still coming up with the original ISISROOT somehow. The only way I found to do this is to change ISISROOT value at the very beginning of login. Thanks for your help though!

**Comment by michaelaye** [comment]
hah, so i thought. Now it's getting weird, the local shell is correctly getting to my CMAKE ISIS3 version, while pysis somehow get's the old install... investigating...
