### ISSUE TITLE
How to use getkey?

### ISSUE THREAD

**Issue by michaelaye** [wtolson/Pysis#2]
In the command line getkey works for me:
```bash
$ getkey from= N1560309735_1.map.cal.cub grpname=mapping keyword=MinimumRingRadius
134218923.81801
```
but with Pysis I just get a 0 back, which I think indicates successful execution, but where's the output?

```python
getkey(from_='N1560309735_1.map.cal.cub', grpname='mapping', keyword='MinimumRingRadius')
0
```

**Comment by wtolson** [comment]
Calling a command will return the status code by default (similar to `subprocess.call`). To get the output, use a commands `check_output` method:

    getkey.check_output(from_='N1560309735_1.map.cal.cub', grpname='mapping', keyword='MinimumRingRadius')

I'll try and update the docs when I get more time, hope that helps!

**Comment by michaelaye** [comment]
i'll make a PR for the main readme, if that's okay for you?

**Comment by wtolson** [comment]
Thanks again.
