### ISSUE TITLE
IsisPool object does not have ISIS functions as attributes

### ISSUE THREAD

**Issue by michaelaye** [wtolson/Pysis#5]
The examples indicates that one can create an IsisPool object like so:

```python
isis_pool = IsisPool()
```
and then access the isis functions, in the example:
```python
isis_pool.md2isis()
```
but the object I created from IsisPool() only has 'close_and_wait',
and 'pool' as attributes? Am I missing something?

**Comment by wtolson** [comment]
`IsisPool` defaults to lazy loading its attributes. So if you call `isis_pool.md2isis()` it will dynamically look it up but it won't tab complete in the shell. However if you initialize `IsisPool` like:

    isis_pool = IsisPool(strict=True)

It will initially resolve all the isis commands and will therefore be available for tab complete.
