### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by michaelaye** [wtolson/Pysis#6]
Hi!
I'm trying to change Pysis to make it support Python 3.
Have done the usual 2to3 stuff and am currently stuck at this:
```python
/Users/klay6683/Dropbox/src/Pysis/pysis/specialpixels.py in <module>()
     79 
     80     'Real': {
---> 81         'Min':  _make_num('\xFF\x7F\xFF\xFA', '>f4'),
     82         'Null': _make_num('\xFF\x7F\xFF\xFB', '>f4'),
     83         'Lrs':  _make_num('\xFF\x7F\xFF\xFC', '>f4'),

/Users/klay6683/Dropbox/src/Pysis/pysis/specialpixels.py in _make_num(num, dtype)
     34 
     35 def _make_num(num, dtype):
---> 36     return np.fromstring(num, dtype=dtype)[0]
     37 
     38 SPECIAL_PIXELS = {

ValueError: string size must be a multiple of element size
```

It must have something with the way Python3 deals with strings differently, I guess?
Do you happen to know how to fix it? In other words, if you'll be the brain, I'll be the fingers (to implement the required changes).. ;)

**Comment by wtolson** [comment]
Yeah, python3 defaults to unicode strings whereas python2 defaults to byte strings, which is what you want for the most part. The problem here is numpy.fromstring expects a byte string. Luckily you can just use a byte string literal (where you prefix the string with `b`) that works in both python 2 and 3 so something like this should work:

    _make_num(b'\xFF\x7F\xFF\xFA', '>f4')

Excited to see someone add python3 compatibility!

**Comment by michaelaye** [comment]
Okay, that worked beautifully! 
Next one is for label parsing:
```python
/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in __init__(self, stream, filename)
    239             self.filename = stream
    240             with open(self.filename) as f:
--> 241                 self._open(f)
    242 
    243         else:

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in _open(self, stream)
    246 
    247     def _open(self, stream):
--> 248         self.label = parse_file_label(stream)
    249         stream.seek(self.start_byte)
    250 

/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in parse_file_label(stream, split_units)
    264         A dictionary representation of the given isis label.
    265     """
--> 266     return parse_label(get_label(stream), split_units=split_units)

/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in get_label(stream, BUF_SIZE)
    224 
    225     label = []
--> 226     buff = stream.read(BUF_SIZE)
    227 
    228     while len(buff):

/Users/klay6683/miniconda3/lib/python3.4/codecs.py in decode(self, input, final)
    317         # decode input (taking the buffer into account)
    318         data = self.buffer + input
--> 319         (result, consumed) = self._buffer_decode(data, self.errors, final)
    320         # keep undecoded input until the next call
    321         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 65536: invalid start byte
```
This looks scary, has it's a simple stream.read() ops that fails inside a Python module? What can be done?

**Comment by wtolson** [comment]
Looks like another python3 encoding error. Files should be opened explicitly in binary mode. Should be able to just change [cubefile.py line 240](https://github.com/wtolson/Pysis/blob/master/pysis/cubefile.py#L240) to:

    with open(self.filename, 'rb') as f:

**Comment by wtolson** [comment]
Probably will need to be fixed in [labels.py line 222](https://github.com/wtolson/Pysis/blob/40642d5d66bfa7601b830bc2cdede4c7b4017ebe/pysis/labels.py#L222) aswell.

**Comment by michaelaye** [comment]
okay, did that, but find a string of new problems:

First error that comes back now (after fixing both occurences above) is this:

```python
/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in _open(self, stream)
    246 
    247     def _open(self, stream):
--> 248         self.label = parse_file_label(stream)
    249         stream.seek(self.start_byte)
    250 

/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in parse_file_label(stream, split_units)
    264         A dictionary representation of the given isis label.
    265     """
--> 266     return parse_label(get_label(stream), split_units=split_units)

/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in get_label(stream, BUF_SIZE)
    227 
    228     while len(buff):
--> 229         label_end = buff.find('\0')
    230 
    231         if label_end == -1:

TypeError: 'str' does not support the buffer interface
```
So I thought, I have seen this before and but a b in front of '\0' to have it interpreted as a byte code.
Then I got this:

```python
/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in parse_file_label(stream, split_units)
    264         A dictionary representation of the given isis label.
    265     """
--> 266     return parse_label(get_label(stream), split_units=split_units)

/Users/klay6683/Dropbox/src/Pysis/pysis/labels.py in get_label(stream, BUF_SIZE)
    237         buff = stream.read(BUF_SIZE)
    238 
--> 239     return ''.join(label)
    240 
    241 

TypeError: sequence item 0: expected str instance, bytes found
```
Here I thought, okay, the label is being read as binary data, but you want a string here, and previously I was solving similar things with a simple str(label) encapsulation, but it did not yet do the job, as I now am getting this:

```python
Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in _open(self, stream)
    247     def _open(self, stream):
    248         self.label = parse_file_label(stream)
--> 249         stream.seek(self.start_byte)
    250 
    251         if self.format == 'BandSequential':

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in start_byte(self)
    218     @property
    219     def start_byte(self):
--> 220         return self.label['IsisCube']['Core']['StartByte'] - 1
    221 
    222     @property

KeyError: 'IsisCube'
```
which most likely means, that the label was not read properly. Any more ideas?

**Comment by wtolson** [comment]
If I'm understanding you correctly you changed labels.py line 239 to  `return ''.join(str(label))`. Try the following instead:

    return b''.join(label)

**Comment by wtolson** [comment]
How goes progress on your side? I'll have some time this weekend to work on this so let me know if there's any particular areas I can help with.

**Comment by wtolson** [comment]
I was able to finish this up over the weekend. Thanks for all your help and feel free to add your name to [AUTHORS.rst](https://github.com/wtolson/Pysis/blob/master/AUTHORS.rst). Let me know how it works for you and any feedback you might have!

**Comment by michaelaye** [comment]
Hey thanks! sorry I was quite, was on travel last week and then this week have to deal with 300 emails from the time I travelled. ;) It just never ends. Do you have tests that can be tried out? If not, should we add some?

**Comment by wtolson** [comment]
I've got some [tests started](https://github.com/wtolson/pysis/tree/master/tests) but coverage could definitely be better!
