### ISSUE TITLE
PEP440 Warning

### ISSUE THREAD

**Issue by YannChemin** [wtolson/pysis#8]
Hey Trevor,

made an easy_install in Ubuntu 15.04, Warns me about this PEP440 thingy.

yann@yann-OK:~/dev$ sudo easy_install pysis
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:2512: PEP440Warning: 'python-apt (0.9.3.11build1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Searching for pysis
Reading https://pypi.python.org/simple/pysis/
Best match: pysis 0.5.0
Downloading https://pypi.python.org/packages/source/p/pysis/pysis-0.5.0.tar.gz#md5=0c55ccf9d694f9d01e41bc4dc5d2234e
Processing pysis-0.5.0.tar.gz
Writing /tmp/easy_install-HaWJJ3/pysis-0.5.0/setup.cfg
Running pysis-0.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HaWJJ3/pysis-0.5.0/egg-dist-tmp-l304Jb
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
creating /usr/local/lib/python2.7/dist-packages/pysis-0.5.0-py2.7.egg
Extracting pysis-0.5.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pysis 0.5.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pysis-0.5.0-py2.7.egg
Processing dependencies for pysis
Finished processing dependencies for pysis

**Comment by YannChemin** [comment]
Oh just realized it maybe python-apt really and not pysis.

**Comment by wtolson** [comment]
I think you're right in that python-apt is triggering the warning. According to [this bug report](https://lists.ubuntu.com/archives/foundations-bugs/2015-April/234753.html) you should be safe in ignoring it. Let me know if you suspect otherwise and I'll reopen the issue.
